version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BradyDB
    # volumes:
    #   - ./data:/var/lib/postgresql/data
